name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-slave:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-Slave
      run: cd slave; cargo build --verbose
  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-Master
      run: cd master; cargo build --verbose
