name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-slave:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-Slave
      run: cd slave; cargo build --verbose
  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-Master
      run: cd master; cargo build --verbose
  build-backup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build-Backup
      run: cd backup; cargo build --verbose
  check-shared-resources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check-Shared-Resources
      run: cd shared_resources; cargo check --verbose
  check-network-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check-Network-Rust
      run: cd network-rust; cargo check --verbose
